var searchData=
[
  ['iapproachingelementlogic_71',['IApproachingElementLogic',['../interface_seal_escape_1_1_logic_1_1_i_approaching_element_logic.html',1,'SealEscape::Logic']]],
  ['iapproachingelementmodel_72',['IApproachingElementModel',['../interface_seal_escape_1_1_model_1_1_i_approaching_element_model.html',1,'SealEscape::Model']]],
  ['ienemylogic_73',['IEnemyLogic',['../interface_seal_escape_1_1_logic_1_1_i_enemy_logic.html',1,'SealEscape::Logic']]],
  ['ienemymodel_74',['IEnemyModel',['../interface_seal_escape_1_1_model_1_1_i_enemy_model.html',1,'SealEscape::Model']]],
  ['ifoodlogic_75',['IFoodLogic',['../interface_seal_escape_1_1_logic_1_1_i_food_logic.html',1,'SealEscape::Logic']]],
  ['ifoodmodel_76',['IFoodModel',['../interface_seal_escape_1_1_model_1_1_i_food_model.html',1,'SealEscape::Model']]],
  ['igameelementlogic_77',['IGameElementLogic',['../interface_seal_escape_1_1_logic_1_1_i_game_element_logic.html',1,'SealEscape::Logic']]],
  ['igameelementmodel_78',['IGameElementModel',['../interface_seal_escape_1_1_model_1_1_i_game_element_model.html',1,'SealEscape::Model']]],
  ['igamelogic_79',['IGameLogic',['../interface_seal_escape_1_1_logic_1_1_i_game_logic.html',1,'SealEscape::Logic']]],
  ['igamemodel_80',['IGameModel',['../interface_seal_escape_1_1_model_1_1_i_game_model.html',1,'SealEscape::Model']]],
  ['ileaderboardentrymodel_81',['ILeaderboardEntryModel',['../interface_seal_escape_1_1_model_1_1_other_models_1_1_interfaces_1_1_i_leaderboard_entry_model.html',1,'SealEscape::Model::OtherModels::Interfaces']]],
  ['imagepath_82',['ImagePath',['../interface_seal_escape_1_1_model_1_1_other_models_1_1_interfaces_1_1_i_shop_item_model.html#af17b93f72b7335b439024d36f5a298e1',1,'SealEscape.Model.OtherModels.Interfaces.IShopItemModel.ImagePath()'],['../class_seal_escape_1_1_model_1_1_other_models_1_1_shop_item_model.html#a75069f94ffe0b20d181b4e34d8d41bc3',1,'SealEscape.Model.OtherModels.ShopItemModel.ImagePath()']]],
  ['imenulogic_83',['IMenuLogic',['../interface_seal_escape_1_1_logic_1_1_i_menu_logic.html',1,'SealEscape::Logic']]],
  ['increasefoodcollected_84',['IncreaseFoodCollected',['../class_seal_escape_1_1_logic_1_1_other_logics_1_1_game_logic.html#a6bca71b65758cd137f8579ed4627830e',1,'SealEscape.Logic.OtherLogics.GameLogic.IncreaseFoodCollected()'],['../interface_seal_escape_1_1_logic_1_1_i_game_logic.html#aa0ab21a2e705f9c1d64e3b53bb71e5f3',1,'SealEscape.Logic.IGameLogic.IncreaseFoodCollected()']]],
  ['increasescore_85',['IncreaseScore',['../class_seal_escape_1_1_logic_1_1_other_logics_1_1_game_logic.html#a8c8961618eb478f65eafd6a21fda9159',1,'SealEscape.Logic.OtherLogics.GameLogic.IncreaseScore()'],['../interface_seal_escape_1_1_logic_1_1_i_game_logic.html#a86e131a7dbf19d3b01e8dce6e42a1e94',1,'SealEscape.Logic.IGameLogic.IncreaseScore()']]],
  ['increasescoreworkscorrectly_86',['IncreaseScoreWorksCorrectly',['../class_seal_escape_1_1_tests_1_1_tests.html#a7ace653bf68ea6704b5d4753d9821fc2',1,'SealEscape::Tests::Tests']]],
  ['increaseslifeby_87',['IncreasesLifeBy',['../interface_seal_escape_1_1_model_1_1_other_models_1_1_interfaces_1_1_i_powerup_model.html#adc08b9fca81363c05024ade5f28d2865',1,'SealEscape.Model.OtherModels.Interfaces.IPowerupModel.IncreasesLifeBy()'],['../class_seal_escape_1_1_model_1_1_other_models_1_1_powerup_model.html#acd59e7ba38ab9fac0c7033ca33fa7ad6',1,'SealEscape.Model.OtherModels.PowerupModel.IncreasesLifeBy()']]],
  ['iplayerlogic_88',['IPlayerLogic',['../interface_seal_escape_1_1_logic_1_1_i_player_logic.html',1,'SealEscape::Logic']]],
  ['iplayermodel_89',['IPlayerModel',['../interface_seal_escape_1_1_model_1_1_i_player_model.html',1,'SealEscape::Model']]],
  ['ipowerupmodel_90',['IPowerupModel',['../interface_seal_escape_1_1_model_1_1_other_models_1_1_interfaces_1_1_i_powerup_model.html',1,'SealEscape::Model::OtherModels::Interfaces']]],
  ['irepointerface_91',['IRepoInterface',['../interface_seal_escape_1_1_repository_1_1_i_repo_interface.html',1,'SealEscape::Repository']]],
  ['irepointerface_3c_20igamemodel_20_3e_92',['IRepoInterface&lt; IGameModel &gt;',['../interface_seal_escape_1_1_repository_1_1_i_repo_interface.html',1,'SealEscape::Repository']]],
  ['irepointerface_3c_20ileaderboardentrymodel_20_3e_93',['IRepoInterface&lt; ILeaderboardEntryModel &gt;',['../interface_seal_escape_1_1_repository_1_1_i_repo_interface.html',1,'SealEscape::Repository']]],
  ['irepointerface_3c_20ishopitemmodel_20_3e_94',['IRepoInterface&lt; IShopItemModel &gt;',['../interface_seal_escape_1_1_repository_1_1_i_repo_interface.html',1,'SealEscape::Repository']]],
  ['iscollision_95',['IsCollision',['../class_seal_escape_1_1_model_1_1_game_element_model.html#a31a86d11e5a8429fec0bb556db0d3655',1,'SealEscape.Model.GameElementModel.IsCollision()'],['../interface_seal_escape_1_1_model_1_1_i_game_element_model.html#a63c76512568ced79c88f589c3d62d8e2',1,'SealEscape.Model.IGameElementModel.IsCollision()']]],
  ['ishopitemmodel_96',['IShopItemModel',['../interface_seal_escape_1_1_model_1_1_other_models_1_1_interfaces_1_1_i_shop_item_model.html',1,'SealEscape::Model::OtherModels::Interfaces']]]
];
